// AUTO-GENERATED by scripts/mine-category-attributes.ts — do not edit by hand.
// Source: regions.json (Jiji Ethiopia regions/cities)

export type Region = {
  id: number;
  parent_id: number | null;
  name: string;
  slug: string;
  parent_ids: number[];
  is_popular: boolean;
};

export const REGIONS: Region[] = [
  {
    "id": 60,
    "parent_id": 8,
    "name": "East Hararghe",
    "slug": "east-hararghe",
    "parent_ids": [
      8
    ],
    "is_popular": false
  },
  {
    "id": 37,
    "parent_id": 3,
    "name": "Bahir Dar",
    "slug": "bahir-dar",
    "parent_ids": [
      3
    ],
    "is_popular": false
  },
  {
    "id": 123,
    "parent_id": 11,
    "name": "Mekelle",
    "slug": "mekelle",
    "parent_ids": [
      11
    ],
    "is_popular": false
  },
  {
    "id": 7,
    "parent_id": null,
    "name": "Harari Region",
    "slug": "harari",
    "parent_ids": [],
    "is_popular": false
  },
  {
    "id": 57,
    "parent_id": 8,
    "name": "Bale",
    "slug": "bale",
    "parent_ids": [
      8
    ],
    "is_popular": false
  },
  {
    "id": 34,
    "parent_id": 3,
    "name": "South Wollo",
    "slug": "south-wollo",
    "parent_ids": [
      3
    ],
    "is_popular": false
  },
  {
    "id": 67,
    "parent_id": 8,
    "name": "Jimma",
    "slug": "jimma",
    "parent_ids": [
      8
    ],
    "is_popular": false
  },
  {
    "id": 78,
    "parent_id": 9,
    "name": "Fafan (Jigjiga)",
    "slug": "fafan",
    "parent_ids": [
      9
    ],
    "is_popular": false
  },
  {
    "id": 2,
    "parent_id": null,
    "name": "Afar Region",
    "slug": "afar",
    "parent_ids": [],
    "is_popular": false
  },
  {
    "id": 31,
    "parent_id": 3,
    "name": "North Shewa",
    "slug": "north-shewa",
    "parent_ids": [
      3
    ],
    "is_popular": false
  },
  {
    "id": 49,
    "parent_id": 7,
    "name": "Shenkor",
    "slug": "shenkor",
    "parent_ids": [
      7
    ],
    "is_popular": false
  },
  {
    "id": 73,
    "parent_id": 8,
    "name": "West Shewa",
    "slug": "west-shewa",
    "parent_ids": [
      8
    ],
    "is_popular": false
  },
  {
    "id": 56,
    "parent_id": 8,
    "name": "Arsi",
    "slug": "arsi",
    "parent_ids": [
      8
    ],
    "is_popular": false
  },
  {
    "id": 30,
    "parent_id": 3,
    "name": "North Gondar",
    "slug": "north-gondar",
    "parent_ids": [
      3
    ],
    "is_popular": false
  },
  {
    "id": 108,
    "parent_id": 10,
    "name": "Wolayita",
    "slug": "wolayita",
    "parent_ids": [
      10
    ],
    "is_popular": false
  },
  {
    "id": 69,
    "parent_id": 8,
    "name": "North Shewa",
    "slug": "north-shewa-oromia",
    "parent_ids": [
      8
    ],
    "is_popular": false
  },
  {
    "id": 71,
    "parent_id": 8,
    "name": "West Arsi",
    "slug": "west-arsi",
    "parent_ids": [
      8
    ],
    "is_popular": false
  },
  {
    "id": 45,
    "parent_id": 6,
    "name": "Nuer",
    "slug": "nuer",
    "parent_ids": [
      6
    ],
    "is_popular": false
  },
  {
    "id": 99,
    "parent_id": 10,
    "name": "Hadiya",
    "slug": "hadiya",
    "parent_ids": [
      10
    ],
    "is_popular": false
  },
  {
    "id": 32,
    "parent_id": 3,
    "name": "North Wollo",
    "slug": "north-wollo",
    "parent_ids": [
      3
    ],
    "is_popular": false
  },
  {
    "id": 95,
    "parent_id": 10,
    "name": "Gamo",
    "slug": "gamo",
    "parent_ids": [
      10
    ],
    "is_popular": false
  },
  {
    "id": 85,
    "parent_id": 9,
    "name": "Afder",
    "slug": "afder",
    "parent_ids": [
      9
    ],
    "is_popular": false
  },
  {
    "id": 72,
    "parent_id": 8,
    "name": "West Hararghe",
    "slug": "west-hararghe",
    "parent_ids": [
      8
    ],
    "is_popular": false
  },
  {
    "id": 86,
    "parent_id": 9,
    "name": "Liben",
    "slug": "liben",
    "parent_ids": [
      9
    ],
    "is_popular": false
  },
  {
    "id": 42,
    "parent_id": 5,
    "name": "Gurgura",
    "slug": "gurgura",
    "parent_ids": [
      5
    ],
    "is_popular": false
  },
  {
    "id": 65,
    "parent_id": 8,
    "name": "Horo Gudru Welega",
    "slug": "horo-gudru-welega",
    "parent_ids": [
      8
    ],
    "is_popular": false
  },
  {
    "id": 1,
    "parent_id": null,
    "name": "Addis Ababa",
    "slug": "addis-ababa",
    "parent_ids": [],
    "is_popular": false
  },
  {
    "id": 15,
    "parent_id": 1,
    "name": "Bole",
    "slug": "bole",
    "parent_ids": [
      1
    ],
    "is_popular": false
  },
  {
    "id": 21,
    "parent_id": 1,
    "name": "Yeka",
    "slug": "yeka",
    "parent_ids": [
      1
    ],
    "is_popular": false
  },
  {
    "id": 12,
    "parent_id": 1,
    "name": "Addis Ketema",
    "slug": "addis-ketema",
    "parent_ids": [
      1
    ],
    "is_popular": false
  },
  {
    "id": 14,
    "parent_id": 1,
    "name": "Arada",
    "slug": "arada",
    "parent_ids": [
      1
    ],
    "is_popular": false
  },
  {
    "id": 20,
    "parent_id": 1,
    "name": "Nifas Silk-Lafto",
    "slug": "nifas-silk-lafto",
    "parent_ids": [
      1
    ],
    "is_popular": false
  },
  {
    "id": 19,
    "parent_id": 1,
    "name": "Lideta",
    "slug": "lideta",
    "parent_ids": [
      1
    ],
    "is_popular": false
  },
  {
    "id": 18,
    "parent_id": 1,
    "name": "Kolfe Keranio",
    "slug": "kolfe-keranio",
    "parent_ids": [
      1
    ],
    "is_popular": false
  },
  {
    "id": 17,
    "parent_id": 1,
    "name": "Kirkos",
    "slug": "kirkos",
    "parent_ids": [
      1
    ],
    "is_popular": false
  },
  {
    "id": 13,
    "parent_id": 1,
    "name": "Akaky Kaliti",
    "slug": "akaky-kaliti",
    "parent_ids": [
      1
    ],
    "is_popular": false
  },
  {
    "id": 16,
    "parent_id": 1,
    "name": "Gullele",
    "slug": "gullele",
    "parent_ids": [
      1
    ],
    "is_popular": false
  },
  {
    "id": 8,
    "parent_id": null,
    "name": "Oromia Region",
    "slug": "oromia",
    "parent_ids": [],
    "is_popular": false
  },
  {
    "id": 75,
    "parent_id": 8,
    "name": "Adama",
    "slug": "adama",
    "parent_ids": [
      8
    ],
    "is_popular": false
  },
  {
    "id": 76,
    "parent_id": 8,
    "name": "Oromia-Finfinne",
    "slug": "oromia-finfinne",
    "parent_ids": [
      8
    ],
    "is_popular": false
  },
  {
    "id": 3,
    "parent_id": null,
    "name": "Amhara Region",
    "slug": "amhara",
    "parent_ids": [],
    "is_popular": false
  },
  {
    "id": 61,
    "parent_id": 8,
    "name": "East Shewa",
    "slug": "east-shewa",
    "parent_ids": [
      8
    ],
    "is_popular": false
  },
  {
    "id": 10,
    "parent_id": null,
    "name": "SNNPR",
    "slug": "snnpr",
    "parent_ids": [],
    "is_popular": false
  },
  {
    "id": 29,
    "parent_id": 3,
    "name": "East Gojjam",
    "slug": "east-gojjam",
    "parent_ids": [
      3
    ],
    "is_popular": false
  },
  {
    "id": 5,
    "parent_id": null,
    "name": "Dire Dawa",
    "slug": "dire-dawa",
    "parent_ids": [],
    "is_popular": false
  },
  {
    "id": 41,
    "parent_id": 5,
    "name": "Dire Dawa city",
    "slug": "dire-dawa-city",
    "parent_ids": [
      5
    ],
    "is_popular": false
  },
  {
    "id": 105,
    "parent_id": 10,
    "name": "Sidama",
    "slug": "sidama",
    "parent_ids": [
      10
    ],
    "is_popular": false
  },
  {
    "id": 11,
    "parent_id": null,
    "name": "Tigray Region",
    "slug": "tigray",
    "parent_ids": [],
    "is_popular": false
  },
  {
    "id": 9,
    "parent_id": null,
    "name": "Somali Region",
    "slug": "somali",
    "parent_ids": [],
    "is_popular": false
  },
  {
    "id": 80,
    "parent_id": 9,
    "name": "Nogob (Fiq)",
    "slug": "nogob",
    "parent_ids": [
      9
    ],
    "is_popular": false
  },
  {
    "id": 59,
    "parent_id": 8,
    "name": "Borena",
    "slug": "borena",
    "parent_ids": [
      8
    ],
    "is_popular": false
  },
  {
    "id": 6,
    "parent_id": null,
    "name": "Gambela Region",
    "slug": "gambela",
    "parent_ids": [],
    "is_popular": false
  },
  {
    "id": 4,
    "parent_id": null,
    "name": "Benishangul-Gumuz Region",
    "slug": "benishangul-gumuz",
    "parent_ids": [],
    "is_popular": false
  },
  {
    "id": 48,
    "parent_id": 7,
    "name": "Abadir",
    "slug": "abadir",
    "parent_ids": [
      7
    ],
    "is_popular": false
  },
  {
    "id": 62,
    "parent_id": 8,
    "name": "East Welega",
    "slug": "east-welega",
    "parent_ids": [
      8
    ],
    "is_popular": false
  },
  {
    "id": 38,
    "parent_id": 4,
    "name": "Asosa",
    "slug": "asosa",
    "parent_ids": [
      4
    ],
    "is_popular": false
  },
  {
    "id": 98,
    "parent_id": 10,
    "name": "Gurage",
    "slug": "gurage",
    "parent_ids": [
      10
    ],
    "is_popular": false
  },
  {
    "id": 70,
    "parent_id": 8,
    "name": "South West Shewa",
    "slug": "south-west-shewa",
    "parent_ids": [
      8
    ],
    "is_popular": false
  },
  {
    "id": 52,
    "parent_id": 7,
    "name": "Hakim",
    "slug": "hakim",
    "parent_ids": [
      7
    ],
    "is_popular": false
  },
  {
    "id": 102,
    "parent_id": 10,
    "name": "Kembata Tembaro",
    "slug": "kembata-tembaro",
    "parent_ids": [
      10
    ],
    "is_popular": false
  },
  {
    "id": 33,
    "parent_id": 3,
    "name": "South Gondar",
    "slug": "south-gondar",
    "parent_ids": [
      3
    ],
    "is_popular": false
  },
  {
    "id": 43,
    "parent_id": 6,
    "name": "Anuak",
    "slug": "anuak",
    "parent_ids": [
      6
    ],
    "is_popular": false
  },
  {
    "id": 63,
    "parent_id": 8,
    "name": "Guji",
    "slug": "guji",
    "parent_ids": [
      8
    ],
    "is_popular": false
  },
  {
    "id": 22,
    "parent_id": 2,
    "name": "Awsi Rasu",
    "slug": "awsi-rasu",
    "parent_ids": [
      2
    ],
    "is_popular": false
  },
  {
    "id": 51,
    "parent_id": 7,
    "name": "Aboker",
    "slug": "aboker",
    "parent_ids": [
      7
    ],
    "is_popular": false
  },
  {
    "id": 74,
    "parent_id": 8,
    "name": "West Welega",
    "slug": "west-welega",
    "parent_ids": [
      8
    ],
    "is_popular": false
  },
  {
    "id": 117,
    "parent_id": 11,
    "name": "Central Tigray",
    "slug": "central-tigray",
    "parent_ids": [
      11
    ],
    "is_popular": false
  },
  {
    "id": 28,
    "parent_id": 3,
    "name": "Agew Awi",
    "slug": "agew-awi",
    "parent_ids": [
      3
    ],
    "is_popular": false
  },
  {
    "id": 36,
    "parent_id": 3,
    "name": "West Gojjam",
    "slug": "west-gojjam",
    "parent_ids": [
      3
    ],
    "is_popular": false
  },
  {
    "id": 96,
    "parent_id": 10,
    "name": "Gofa",
    "slug": "gofa",
    "parent_ids": [
      10
    ],
    "is_popular": false
  },
  {
    "id": 97,
    "parent_id": 10,
    "name": "Gedeo",
    "slug": "gedeo",
    "parent_ids": [
      10
    ],
    "is_popular": false
  },
  {
    "id": 90,
    "parent_id": 9,
    "name": "Kebri Beyah",
    "slug": "kebri-beyah",
    "parent_ids": [
      9
    ],
    "is_popular": false
  },
  {
    "id": 35,
    "parent_id": 3,
    "name": "Wag Hemra",
    "slug": "wag-hemra",
    "parent_ids": [
      3
    ],
    "is_popular": false
  },
  {
    "id": 112,
    "parent_id": 10,
    "name": "Burji",
    "slug": "burji",
    "parent_ids": [
      10
    ],
    "is_popular": false
  },
  {
    "id": 121,
    "parent_id": 11,
    "name": "South East Tigray",
    "slug": "south-east-tigray",
    "parent_ids": [
      11
    ],
    "is_popular": false
  },
  {
    "id": 27,
    "parent_id": 2,
    "name": "Argobba",
    "slug": "argobba",
    "parent_ids": [
      2
    ],
    "is_popular": false
  },
  {
    "id": 64,
    "parent_id": 8,
    "name": "West Guji",
    "slug": "west-guji",
    "parent_ids": [
      8
    ],
    "is_popular": false
  },
  {
    "id": 58,
    "parent_id": 8,
    "name": "Bedele",
    "slug": "bedele",
    "parent_ids": [
      8
    ],
    "is_popular": false
  },
  {
    "id": 50,
    "parent_id": 7,
    "name": "Jin'Eala",
    "slug": "jin-eala",
    "parent_ids": [
      7
    ],
    "is_popular": false
  },
  {
    "id": 25,
    "parent_id": 2,
    "name": "Fanti Rasu",
    "slug": "fanti-rasu",
    "parent_ids": [
      2
    ],
    "is_popular": false
  },
  {
    "id": 94,
    "parent_id": 10,
    "name": "Dawro",
    "slug": "dawro",
    "parent_ids": [
      10
    ],
    "is_popular": false
  },
  {
    "id": 106,
    "parent_id": 10,
    "name": "Silti",
    "slug": "silti",
    "parent_ids": [
      10
    ],
    "is_popular": false
  },
  {
    "id": 119,
    "parent_id": 11,
    "name": "North West Tigray",
    "slug": "north-west-tigray",
    "parent_ids": [
      11
    ],
    "is_popular": false
  },
  {
    "id": 24,
    "parent_id": 2,
    "name": "Gabi Rasu",
    "slug": "gabi-rasu",
    "parent_ids": [
      2
    ],
    "is_popular": false
  },
  {
    "id": 100,
    "parent_id": 10,
    "name": "Keffa",
    "slug": "keffa",
    "parent_ids": [
      10
    ],
    "is_popular": false
  },
  {
    "id": 66,
    "parent_id": 8,
    "name": "Illubabor",
    "slug": "illubabor",
    "parent_ids": [
      8
    ],
    "is_popular": false
  },
  {
    "id": 107,
    "parent_id": 10,
    "name": "South Omo",
    "slug": "south-omo",
    "parent_ids": [
      10
    ],
    "is_popular": false
  },
  {
    "id": 47,
    "parent_id": 7,
    "name": "Amir-Nur",
    "slug": "amir-nur",
    "parent_ids": [
      7
    ],
    "is_popular": false
  },
  {
    "id": 89,
    "parent_id": 9,
    "name": "Gode",
    "slug": "gode",
    "parent_ids": [
      9
    ],
    "is_popular": false
  },
  {
    "id": 120,
    "parent_id": 11,
    "name": "South Tigray",
    "slug": "south-tigray",
    "parent_ids": [
      11
    ],
    "is_popular": false
  },
  {
    "id": 44,
    "parent_id": 6,
    "name": "Mezhenger",
    "slug": "mezhenger",
    "parent_ids": [
      6
    ],
    "is_popular": false
  },
  {
    "id": 68,
    "parent_id": 8,
    "name": "Kelem Welega",
    "slug": "kelem-welega",
    "parent_ids": [
      8
    ],
    "is_popular": false
  },
  {
    "id": 93,
    "parent_id": 10,
    "name": "Bench Maji",
    "slug": "bench-maji",
    "parent_ids": [
      10
    ],
    "is_popular": false
  },
  {
    "id": 118,
    "parent_id": 11,
    "name": "East Tigray",
    "slug": "east-tigray",
    "parent_ids": [
      11
    ],
    "is_popular": false
  },
  {
    "id": 40,
    "parent_id": 4,
    "name": "Metekel",
    "slug": "metekel",
    "parent_ids": [
      4
    ],
    "is_popular": false
  },
  {
    "id": 109,
    "parent_id": 10,
    "name": "Alaba",
    "slug": "alaba",
    "parent_ids": [
      10
    ],
    "is_popular": false
  },
  {
    "id": 114,
    "parent_id": 10,
    "name": "Konso",
    "slug": "konso",
    "parent_ids": [
      10
    ],
    "is_popular": false
  },
  {
    "id": 23,
    "parent_id": 2,
    "name": "Kilbati Rasu",
    "slug": "kilbati-rasu",
    "parent_ids": [
      2
    ],
    "is_popular": false
  },
  {
    "id": 79,
    "parent_id": 9,
    "name": "Jarar (Degehabur)",
    "slug": "jarar",
    "parent_ids": [
      9
    ],
    "is_popular": false
  },
  {
    "id": 104,
    "parent_id": 10,
    "name": "Sheka",
    "slug": "sheka",
    "parent_ids": [
      10
    ],
    "is_popular": false
  },
  {
    "id": 77,
    "parent_id": 9,
    "name": "Sitti (Shinile)",
    "slug": "sitti",
    "parent_ids": [
      9
    ],
    "is_popular": false
  },
  {
    "id": 88,
    "parent_id": 9,
    "name": "Tog Wajale",
    "slug": "tog-wajale",
    "parent_ids": [
      9
    ],
    "is_popular": false
  },
  {
    "id": 55,
    "parent_id": 7,
    "name": "Dire-Teyara",
    "slug": "dire-teyara",
    "parent_ids": [
      7
    ],
    "is_popular": false
  },
  {
    "id": 91,
    "parent_id": 9,
    "name": "Degehabur",
    "slug": "degehabur",
    "parent_ids": [
      9
    ],
    "is_popular": false
  },
  {
    "id": 84,
    "parent_id": 9,
    "name": "Shabelle (Godey)",
    "slug": "shabelle",
    "parent_ids": [
      9
    ],
    "is_popular": false
  },
  {
    "id": 39,
    "parent_id": 4,
    "name": "Kamashi",
    "slug": "kamashi",
    "parent_ids": [
      4
    ],
    "is_popular": false
  },
  {
    "id": 54,
    "parent_id": 7,
    "name": "Erer",
    "slug": "erer",
    "parent_ids": [
      7
    ],
    "is_popular": false
  },
  {
    "id": 83,
    "parent_id": 9,
    "name": "Korahe",
    "slug": "korahe",
    "parent_ids": [
      9
    ],
    "is_popular": false
  },
  {
    "id": 110,
    "parent_id": 10,
    "name": "Amaro",
    "slug": "amaro",
    "parent_ids": [
      10
    ],
    "is_popular": false
  },
  {
    "id": 26,
    "parent_id": 2,
    "name": "Harri Rasu",
    "slug": "harri-rasu",
    "parent_ids": [
      2
    ],
    "is_popular": false
  },
  {
    "id": 46,
    "parent_id": 6,
    "name": "Itang",
    "slug": "itang",
    "parent_ids": [
      6
    ],
    "is_popular": false
  },
  {
    "id": 53,
    "parent_id": 7,
    "name": "Sofi",
    "slug": "sofi",
    "parent_ids": [
      7
    ],
    "is_popular": false
  },
  {
    "id": 92,
    "parent_id": 9,
    "name": "Dawa",
    "slug": "dawa",
    "parent_ids": [
      9
    ],
    "is_popular": false
  },
  {
    "id": 101,
    "parent_id": 10,
    "name": "Keficho Shekicho",
    "slug": "keficho-shekicho",
    "parent_ids": [
      10
    ],
    "is_popular": false
  },
  {
    "id": 103,
    "parent_id": 10,
    "name": "North Omo",
    "slug": "north-omo",
    "parent_ids": [
      10
    ],
    "is_popular": false
  },
  {
    "id": 115,
    "parent_id": 10,
    "name": "Konta",
    "slug": "konta",
    "parent_ids": [
      10
    ],
    "is_popular": false
  },
  {
    "id": 122,
    "parent_id": 11,
    "name": "West Tigray",
    "slug": "west-tigray",
    "parent_ids": [
      11
    ],
    "is_popular": false
  },
  {
    "id": 82,
    "parent_id": 9,
    "name": "Dollo (Warder)",
    "slug": "dollo",
    "parent_ids": [
      9
    ],
    "is_popular": false
  },
  {
    "id": 116,
    "parent_id": 10,
    "name": "Yem",
    "slug": "yem",
    "parent_ids": [
      10
    ],
    "is_popular": false
  },
  {
    "id": 111,
    "parent_id": 10,
    "name": "Basketo",
    "slug": "basketo",
    "parent_ids": [
      10
    ],
    "is_popular": false
  },
  {
    "id": 81,
    "parent_id": 9,
    "name": "Erer",
    "slug": "erer-somali",
    "parent_ids": [
      9
    ],
    "is_popular": false
  },
  {
    "id": 87,
    "parent_id": 9,
    "name": "Harawo",
    "slug": "harawo",
    "parent_ids": [
      9
    ],
    "is_popular": false
  },
  {
    "id": 113,
    "parent_id": 10,
    "name": "Dirashe",
    "slug": "dirashe",
    "parent_ids": [
      10
    ],
    "is_popular": false
  }
];

/** Top-level regions (parent_id is null). */
export const TOP_REGIONS: Region[] = REGIONS.filter((r) => r.parent_id === null);

/** Cities/areas under a given parent region id. */
export function regionsByParent(parentId: number): Region[] {
  return REGIONS.filter((r) => r.parent_id === parentId);
}

/** Search regions by name (case-insensitive substring). */
export function searchRegions(query: string, limit = 20): Region[] {
  const q = query.trim().toLowerCase();
  if (!q) return TOP_REGIONS.slice(0, limit);
  return REGIONS.filter((r) => r.name.toLowerCase().includes(q)).slice(0, limit);
}

