// AUTO-GENERATED by scripts/mine-category-attributes.ts — do not edit by hand.
// Source: categories.json (Jiji Ethiopia taxonomy, 17 top-level groups)

export type TaxonomyEntry = {
  id: number;
  slug: string;
  name: string;
  path: string;
  group: string;
};

export const TAXONOMY_ENTRIES: TaxonomyEntry[] = [
  {
    "id": 6,
    "slug": "vehicles",
    "name": "Vehicles",
    "path": "Vehicles",
    "group": "Vehicles"
  },
  {
    "id": 29,
    "slug": "cars",
    "name": "Cars",
    "path": "Vehicles > Cars",
    "group": "Vehicles"
  },
  {
    "id": 382,
    "slug": "buses",
    "name": "Buses & Microbuses",
    "path": "Vehicles > Buses & Microbuses",
    "group": "Vehicles"
  },
  {
    "id": 274,
    "slug": "heavy-equipments-machinery",
    "name": "Construction & Heavy Machinery",
    "path": "Vehicles > Construction & Heavy Machinery",
    "group": "Vehicles"
  },
  {
    "id": 30,
    "slug": "motorcycles-and-scooters",
    "name": "Motorcycles & Scooters",
    "path": "Vehicles > Motorcycles & Scooters",
    "group": "Vehicles"
  },
  {
    "id": 31,
    "slug": "trucks-commercial-agricultiral",
    "name": "Trucks & Trailers",
    "path": "Vehicles > Trucks & Trailers",
    "group": "Vehicles"
  },
  {
    "id": 12,
    "slug": "car-parts-and-accessories",
    "name": "Vehicle Parts & Accessories",
    "path": "Vehicles > Vehicle Parts & Accessories",
    "group": "Vehicles"
  },
  {
    "id": 275,
    "slug": "watercrafts-vehicle",
    "name": "Watercraft & Boats",
    "path": "Vehicles > Watercraft & Boats",
    "group": "Vehicles"
  },
  {
    "id": 9,
    "slug": "real-estate",
    "name": "Property",
    "path": "Property",
    "group": "Property"
  },
  {
    "id": 395,
    "slug": "new-builds",
    "name": "New Builds",
    "path": "Property > New Builds",
    "group": "Property"
  },
  {
    "id": 42,
    "slug": "houses-apartments-for-rent",
    "name": "Houses & Apartments for Rent",
    "path": "Property > Houses & Apartments for Rent",
    "group": "Property"
  },
  {
    "id": 43,
    "slug": "houses-apartments-for-sale",
    "name": "Houses & Apartments for Sale",
    "path": "Property > Houses & Apartments for Sale",
    "group": "Property"
  },
  {
    "id": 283,
    "slug": "land-and-plots-for-rent",
    "name": "Land & Plots for Rent",
    "path": "Property > Land & Plots for Rent",
    "group": "Property"
  },
  {
    "id": 44,
    "slug": "land-and-plots-for-sale",
    "name": "Land & Plots for Sale",
    "path": "Property > Land & Plots for Sale",
    "group": "Property"
  },
  {
    "id": 278,
    "slug": "commercial-property-for-rent",
    "name": "Commercial Property for Rent",
    "path": "Property > Commercial Property for Rent",
    "group": "Property"
  },
  {
    "id": 46,
    "slug": "commercial-properties",
    "name": "Commercial Property for Sale",
    "path": "Property > Commercial Property for Sale",
    "group": "Property"
  },
  {
    "id": 277,
    "slug": "event-centers-and-venues",
    "name": "Event Centres, Venues & Workstations",
    "path": "Property > Event Centres, Venues & Workstations",
    "group": "Property"
  },
  {
    "id": 45,
    "slug": "temporary-and-vacation-rentals",
    "name": "Short Let Property",
    "path": "Property > Short Let Property",
    "group": "Property"
  },
  {
    "id": 1,
    "slug": "mobile-phones-tablets",
    "name": "Phones & Tablets",
    "path": "Phones & Tablets",
    "group": "Phones & Tablets"
  },
  {
    "id": 14,
    "slug": "mobile-phones",
    "name": "Mobile Phones",
    "path": "Phones & Tablets > Mobile Phones",
    "group": "Phones & Tablets"
  },
  {
    "id": 11,
    "slug": "cell-phones-tablets-accessories",
    "name": "Accessories for Phones & Tablets",
    "path": "Phones & Tablets > Accessories for Phones & Tablets",
    "group": "Phones & Tablets"
  },
  {
    "id": 383,
    "slug": "smart-watches",
    "name": "Smart Watches",
    "path": "Phones & Tablets > Smart Watches",
    "group": "Phones & Tablets"
  },
  {
    "id": 15,
    "slug": "tablets",
    "name": "Tablets",
    "path": "Phones & Tablets > Tablets",
    "group": "Phones & Tablets"
  },
  {
    "id": 3,
    "slug": "electronics",
    "name": "Electronics",
    "path": "Electronics",
    "group": "Electronics"
  },
  {
    "id": 388,
    "slug": "accessories-and-supplies-for-electronics",
    "name": "Accessories & Supplies for Electronics",
    "path": "Electronics > Accessories & Supplies for Electronics",
    "group": "Electronics"
  },
  {
    "id": 16,
    "slug": "computers-and-laptops",
    "name": "Laptops & Computers",
    "path": "Electronics > Laptops & Computers",
    "group": "Electronics"
  },
  {
    "id": 17,
    "slug": "tv-dvd-equipment",
    "name": "TV & DVD Equipment",
    "path": "Electronics > TV & DVD Equipment",
    "group": "Electronics"
  },
  {
    "id": 51,
    "slug": "audio-and-music-equipment",
    "name": "Audio & Music Equipment",
    "path": "Electronics > Audio & Music Equipment",
    "group": "Electronics"
  },
  {
    "id": 172,
    "slug": "computer-accessories",
    "name": "Computer Accessories ",
    "path": "Electronics > Computer Accessories ",
    "group": "Electronics"
  },
  {
    "id": 284,
    "slug": "computer-hardware",
    "name": "Computer Hardware",
    "path": "Electronics > Computer Hardware",
    "group": "Electronics"
  },
  {
    "id": 348,
    "slug": "computer-monitors",
    "name": "Monitors",
    "path": "Electronics > Monitors",
    "group": "Electronics"
  },
  {
    "id": 384,
    "slug": "headphones",
    "name": "Headphones",
    "path": "Electronics > Headphones",
    "group": "Electronics"
  },
  {
    "id": 386,
    "slug": "networking-products",
    "name": "Networking Products",
    "path": "Electronics > Networking Products",
    "group": "Electronics"
  },
  {
    "id": 18,
    "slug": "cameras-video-cameras-and-accessories",
    "name": "Photo & Video Cameras",
    "path": "Electronics > Photo & Video Cameras",
    "group": "Electronics"
  },
  {
    "id": 385,
    "slug": "printers-and-scanners",
    "name": "Printers & Scanners",
    "path": "Electronics > Printers & Scanners",
    "group": "Electronics"
  },
  {
    "id": 387,
    "slug": "security-and-surveillance",
    "name": "Security & Surveillance",
    "path": "Electronics > Security & Surveillance",
    "group": "Electronics"
  },
  {
    "id": 312,
    "slug": "computer-software",
    "name": "Software",
    "path": "Electronics > Software",
    "group": "Electronics"
  },
  {
    "id": 270,
    "slug": "videogames",
    "name": "Video Games",
    "path": "Electronics > Video Games",
    "group": "Electronics"
  },
  {
    "id": 19,
    "slug": "video-games-and-consoles",
    "name": "Video Game Consoles",
    "path": "Electronics > Video Game Consoles",
    "group": "Electronics"
  },
  {
    "id": 4,
    "slug": "home-garden",
    "name": "Home, Furniture & Appliances",
    "path": "Home, Furniture & Appliances",
    "group": "Home, Furniture & Appliances"
  },
  {
    "id": 397,
    "slug": "lighting",
    "name": "Lighting",
    "path": "Home, Furniture & Appliances > Lighting",
    "group": "Home, Furniture & Appliances"
  },
  {
    "id": 399,
    "slug": "storage-organization",
    "name": "Storage & Organization",
    "path": "Home, Furniture & Appliances > Storage & Organization",
    "group": "Home, Furniture & Appliances"
  },
  {
    "id": 20,
    "slug": "furniture",
    "name": "Furniture",
    "path": "Home, Furniture & Appliances > Furniture",
    "group": "Home, Furniture & Appliances"
  },
  {
    "id": 21,
    "slug": "garden",
    "name": "Garden Supplies",
    "path": "Home, Furniture & Appliances > Garden Supplies",
    "group": "Home, Furniture & Appliances"
  },
  {
    "id": 53,
    "slug": "decor-accessories",
    "name": "Home Accessories",
    "path": "Home, Furniture & Appliances > Home Accessories",
    "group": "Home, Furniture & Appliances"
  },
  {
    "id": 22,
    "slug": "home-appliances",
    "name": "Home Appliances",
    "path": "Home, Furniture & Appliances > Home Appliances",
    "group": "Home, Furniture & Appliances"
  },
  {
    "id": 279,
    "slug": "kitchen-appliances",
    "name": "Kitchen Appliances",
    "path": "Home, Furniture & Appliances > Kitchen Appliances",
    "group": "Home, Furniture & Appliances"
  },
  {
    "id": 280,
    "slug": "kitchen-and-dining",
    "name": "Kitchenware & Cookware",
    "path": "Home, Furniture & Appliances > Kitchenware & Cookware",
    "group": "Home, Furniture & Appliances"
  },
  {
    "id": 392,
    "slug": "household-chemicals",
    "name": "Household Chemicals",
    "path": "Home, Furniture & Appliances > Household Chemicals",
    "group": "Home, Furniture & Appliances"
  },
  {
    "id": 27,
    "slug": "health-and-beauty",
    "name": "Beauty & Personal Care",
    "path": "Beauty & Personal Care",
    "group": "Beauty & Personal Care"
  },
  {
    "id": 402,
    "slug": "oral-care",
    "name": "Oral Care",
    "path": "Beauty & Personal Care > Oral Care",
    "group": "Beauty & Personal Care"
  },
  {
    "id": 256,
    "slug": "bath-body",
    "name": "Body Care",
    "path": "Beauty & Personal Care > Body Care",
    "group": "Beauty & Personal Care"
  },
  {
    "id": 255,
    "slug": "fragrance",
    "name": "Fragrances",
    "path": "Beauty & Personal Care > Fragrances",
    "group": "Beauty & Personal Care"
  },
  {
    "id": 257,
    "slug": "hair-beauty",
    "name": "Hair Beauty",
    "path": "Beauty & Personal Care > Hair Beauty",
    "group": "Beauty & Personal Care"
  },
  {
    "id": 251,
    "slug": "makeup",
    "name": "Make-Up",
    "path": "Beauty & Personal Care > Make-Up",
    "group": "Beauty & Personal Care"
  },
  {
    "id": 253,
    "slug": "sexual-wellness",
    "name": "Sexual Wellness",
    "path": "Beauty & Personal Care > Sexual Wellness",
    "group": "Beauty & Personal Care"
  },
  {
    "id": 252,
    "slug": "skin-care",
    "name": "Face Care",
    "path": "Beauty & Personal Care > Face Care",
    "group": "Beauty & Personal Care"
  },
  {
    "id": 254,
    "slug": "tools-accessories",
    "name": "Tools & Accessories",
    "path": "Beauty & Personal Care > Tools & Accessories",
    "group": "Beauty & Personal Care"
  },
  {
    "id": 258,
    "slug": "supplements",
    "name": "Vitamins & Supplements",
    "path": "Beauty & Personal Care > Vitamins & Supplements",
    "group": "Beauty & Personal Care"
  },
  {
    "id": 5,
    "slug": "fashion-and-beauty",
    "name": "Fashion",
    "path": "Fashion",
    "group": "Fashion"
  },
  {
    "id": 169,
    "slug": "bags",
    "name": "Bags",
    "path": "Fashion > Bags",
    "group": "Fashion"
  },
  {
    "id": 25,
    "slug": "clothing",
    "name": "Clothing",
    "path": "Fashion > Clothing",
    "group": "Fashion"
  },
  {
    "id": 56,
    "slug": "accessories",
    "name": "Clothing Accessories",
    "path": "Fashion > Clothing Accessories",
    "group": "Fashion"
  },
  {
    "id": 26,
    "slug": "jewellery-and-watches",
    "name": "Jewelry",
    "path": "Fashion > Jewelry",
    "group": "Fashion"
  },
  {
    "id": 55,
    "slug": "shoes",
    "name": "Shoes",
    "path": "Fashion > Shoes",
    "group": "Fashion"
  },
  {
    "id": 168,
    "slug": "watches",
    "name": "Watches",
    "path": "Fashion > Watches",
    "group": "Fashion"
  },
  {
    "id": 57,
    "slug": "wedding-wear",
    "name": "Wedding Wear & Accessories",
    "path": "Fashion > Wedding Wear & Accessories",
    "group": "Fashion"
  },
  {
    "id": 8,
    "slug": "hobbies-art-sport",
    "name": "Leisure & Activities",
    "path": "Leisure & Activities",
    "group": "Leisure & Activities"
  },
  {
    "id": 259,
    "slug": "massagers",
    "name": "Massagers",
    "path": "Leisure & Activities > Massagers",
    "group": "Leisure & Activities"
  },
  {
    "id": 38,
    "slug": "art-collectibles",
    "name": "Arts, Crafts & Awards",
    "path": "Leisure & Activities > Arts, Crafts & Awards",
    "group": "Leisure & Activities"
  },
  {
    "id": 36,
    "slug": "books-and-games",
    "name": "Books & Table Games",
    "path": "Leisure & Activities > Books & Table Games",
    "group": "Leisure & Activities"
  },
  {
    "id": 76,
    "slug": "camping-gear",
    "name": "Outdoor Gear",
    "path": "Leisure & Activities > Outdoor Gear",
    "group": "Leisure & Activities"
  },
  {
    "id": 75,
    "slug": "cds-and-dvds",
    "name": "Music & Video",
    "path": "Leisure & Activities > Music & Video",
    "group": "Leisure & Activities"
  },
  {
    "id": 37,
    "slug": "musical-instruments",
    "name": "Musical Instruments & Gear",
    "path": "Leisure & Activities > Musical Instruments & Gear",
    "group": "Leisure & Activities"
  },
  {
    "id": 40,
    "slug": "sports-bicycles-and-fitness",
    "name": "Sports Equipment",
    "path": "Leisure & Activities > Sports Equipment",
    "group": "Leisure & Activities"
  },
  {
    "id": 403,
    "slug": "personal-mobility",
    "name": "Personal Mobility",
    "path": "Leisure & Activities > Personal Mobility",
    "group": "Leisure & Activities"
  },
  {
    "id": 389,
    "slug": "hookah-and-vaporizers",
    "name": "Smoking Accessories",
    "path": "Leisure & Activities > Smoking Accessories",
    "group": "Leisure & Activities"
  },
  {
    "id": 110,
    "slug": "seeking-work-cvs",
    "name": "Seeking Work CVs",
    "path": "Seeking Work CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 111,
    "slug": "accounting-and-finance-cvs",
    "name": "Accounting & Finance CVs",
    "path": "Seeking Work CVs > Accounting & Finance CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 112,
    "slug": "advertising-and-marketing-cvs",
    "name": "Advertising & Marketing CVs",
    "path": "Seeking Work CVs > Advertising & Marketing CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 113,
    "slug": "arts-and-entertainment-cvs",
    "name": "Arts & Entertainment CVs",
    "path": "Seeking Work CVs > Arts & Entertainment CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 114,
    "slug": "childcare-and-babysitting-cvs",
    "name": "Childcare & Babysitting CVs",
    "path": "Seeking Work CVs > Childcare & Babysitting CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 115,
    "slug": "clerical-and-administrative-cvs",
    "name": "Clerical & Administrative CVs",
    "path": "Seeking Work CVs > Clerical & Administrative CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 116,
    "slug": "computing-and-it-cvs",
    "name": "Computing & IT CVs",
    "path": "Seeking Work CVs > Computing & IT CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 117,
    "slug": "construction-and-skilled-trade-cvs",
    "name": "Construction & Skilled Trade CVs",
    "path": "Seeking Work CVs > Construction & Skilled Trade CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 313,
    "slug": "consulting-and-strategy-cvs",
    "name": "Consulting & Strategy CVs",
    "path": "Seeking Work CVs > Consulting & Strategy CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 118,
    "slug": "customer-service-cvs",
    "name": "Customer Services CVs",
    "path": "Seeking Work CVs > Customer Services CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 265,
    "slug": "driver-cvs",
    "name": "Driver CVs",
    "path": "Seeking Work CVs > Driver CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 119,
    "slug": "engineering-and-architecture-cvs",
    "name": "Engineering & Architecture CVs",
    "path": "Seeking Work CVs > Engineering & Architecture CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 120,
    "slug": "farming-and-veterinary-cvs",
    "name": "Farming & Veterinary CVs",
    "path": "Seeking Work CVs > Farming & Veterinary CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 121,
    "slug": "gardening-and-landscaping-cvs",
    "name": "Gardening & Landscaping CVs",
    "path": "Seeking Work CVs > Gardening & Landscaping CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 122,
    "slug": "health-and-beauty-cvs",
    "name": "Health & Beauty CVs",
    "path": "Seeking Work CVs > Health & Beauty CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 123,
    "slug": "healthcare-and-nursing-cvs",
    "name": "Healthcare & Nursing CVs",
    "path": "Seeking Work CVs > Healthcare & Nursing CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 266,
    "slug": "hotel-cvs",
    "name": "Hotel CVs",
    "path": "Seeking Work CVs > Hotel CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 124,
    "slug": "housekeeping-and-cleaning-cvs",
    "name": "Housekeeping & Cleaning CVs",
    "path": "Seeking Work CVs > Housekeeping & Cleaning CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 125,
    "slug": "human-resources-cvs",
    "name": "Human Resources CVs",
    "path": "Seeking Work CVs > Human Resources CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 126,
    "slug": "internship-cvs",
    "name": "Internship CVs",
    "path": "Seeking Work CVs > Internship CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 127,
    "slug": "legal-cvs",
    "name": "Legal CVs",
    "path": "Seeking Work CVs > Legal CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 128,
    "slug": "logistics-and-transportation-cvs",
    "name": "Logistics & Transportation CVs",
    "path": "Seeking Work CVs > Logistics & Transportation CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 314,
    "slug": "management-cvs",
    "name": "Management CVs",
    "path": "Seeking Work CVs > Management CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 129,
    "slug": "manual-labour-cvs",
    "name": "Manual Labour CVs",
    "path": "Seeking Work CVs > Manual Labour CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 267,
    "slug": "manufacturing-cvs",
    "name": "Manufacturing CVs",
    "path": "Seeking Work CVs > Manufacturing CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 130,
    "slug": "mining-industry-cvs",
    "name": "Mining Industry CVs",
    "path": "Seeking Work CVs > Mining Industry CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 131,
    "slug": "office-cvs",
    "name": "Office CVs",
    "path": "Seeking Work CVs > Office CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 268,
    "slug": "part-time-and-weekend-cvs",
    "name": "Part-Time & Weekend CVs",
    "path": "Seeking Work CVs > Part-Time & Weekend CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 315,
    "slug": "quality-control-and-assurance-cvs",
    "name": "Quality Control & Assurance CVs",
    "path": "Seeking Work CVs > Quality Control & Assurance CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 316,
    "slug": "research-and-survey-cvs",
    "name": "Research & Survey CVs",
    "path": "Seeking Work CVs > Research & Survey CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 132,
    "slug": "restaurant-and-bar-cvs",
    "name": "Restaurant & Bar CVs",
    "path": "Seeking Work CVs > Restaurant & Bar CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 133,
    "slug": "retail-cvs",
    "name": "Retail CVs",
    "path": "Seeking Work CVs > Retail CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 134,
    "slug": "sales-and-telemarketing-cvs",
    "name": "Sales & Telemarketing CVs",
    "path": "Seeking Work CVs > Sales & Telemarketing CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 135,
    "slug": "security-cvs",
    "name": "Security CVs",
    "path": "Seeking Work CVs > Security CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 136,
    "slug": "sports-club-cvs",
    "name": "Sports Club CVs",
    "path": "Seeking Work CVs > Sports Club CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 137,
    "slug": "teaching-cvs",
    "name": "Teaching CVs",
    "path": "Seeking Work CVs > Teaching CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 269,
    "slug": "technology-cvs",
    "name": "Technology CVs",
    "path": "Seeking Work CVs > Technology CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 138,
    "slug": "travel-and-tourism-cvs",
    "name": "Travel & Tourism CVs",
    "path": "Seeking Work CVs > Travel & Tourism CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 139,
    "slug": "other-cvs",
    "name": "Other CVs",
    "path": "Seeking Work CVs > Other CVs",
    "group": "Seeking Work CVs"
  },
  {
    "id": 140,
    "slug": "services",
    "name": "Services",
    "path": "Services",
    "group": "Services"
  },
  {
    "id": 141,
    "slug": "automotive-services",
    "name": "Automotive Services",
    "path": "Services > Automotive Services",
    "group": "Services"
  },
  {
    "id": 142,
    "slug": "building-and-trades-services",
    "name": "Building & Trade Services",
    "path": "Services > Building & Trade Services",
    "group": "Services"
  },
  {
    "id": 143,
    "slug": "chauffeur-and-airport-transfer-services",
    "name": "Chauffeur & Airport Transfer Services",
    "path": "Services > Chauffeur & Airport Transfer Services",
    "group": "Services"
  },
  {
    "id": 144,
    "slug": "child-care-and-education-services",
    "name": "Child Care & Education Services",
    "path": "Services > Child Care & Education Services",
    "group": "Services"
  },
  {
    "id": 160,
    "slug": "classes-and-courses",
    "name": "Classes & Courses",
    "path": "Services > Classes & Courses",
    "group": "Services"
  },
  {
    "id": 145,
    "slug": "cleaning-services",
    "name": "Cleaning Services",
    "path": "Services > Cleaning Services",
    "group": "Services"
  },
  {
    "id": 162,
    "slug": "computer-and-it-services",
    "name": "Computer & IT Services",
    "path": "Services > Computer & IT Services",
    "group": "Services"
  },
  {
    "id": 146,
    "slug": "dj-and-entertainment-services",
    "name": "DJ & Entertainment Services",
    "path": "Services > DJ & Entertainment Services",
    "group": "Services"
  },
  {
    "id": 149,
    "slug": "fitness-and-personal-training-services",
    "name": "Fitness & Personal Training Services",
    "path": "Services > Fitness & Personal Training Services",
    "group": "Services"
  },
  {
    "id": 148,
    "slug": "health-and-beauty-services",
    "name": "Health & Beauty Services",
    "path": "Services > Health & Beauty Services",
    "group": "Services"
  },
  {
    "id": 150,
    "slug": "landscaping-and-gardening-services",
    "name": "Landscaping & Gardening Services",
    "path": "Services > Landscaping & Gardening Services",
    "group": "Services"
  },
  {
    "id": 151,
    "slug": "legal-services",
    "name": "Legal Services",
    "path": "Services > Legal Services",
    "group": "Services"
  },
  {
    "id": 156,
    "slug": "removals-and-storage-services",
    "name": "Logistics Services",
    "path": "Services > Logistics Services",
    "group": "Services"
  },
  {
    "id": 152,
    "slug": "manufacturing-services",
    "name": "Manufacturing Services",
    "path": "Services > Manufacturing Services",
    "group": "Services"
  },
  {
    "id": 147,
    "slug": "party-catering-and-event-services",
    "name": "Party, Catering & Event Services",
    "path": "Services > Party, Catering & Event Services",
    "group": "Services"
  },
  {
    "id": 153,
    "slug": "pet-services",
    "name": "Pet Services",
    "path": "Services > Pet Services",
    "group": "Services"
  },
  {
    "id": 154,
    "slug": "photography-and-video-services",
    "name": "Photography & Video Services",
    "path": "Services > Photography & Video Services",
    "group": "Services"
  },
  {
    "id": 390,
    "slug": "printing-services",
    "name": "Printing Services",
    "path": "Services > Printing Services",
    "group": "Services"
  },
  {
    "id": 155,
    "slug": "recruitment-services",
    "name": "Recruitment Services",
    "path": "Services > Recruitment Services",
    "group": "Services"
  },
  {
    "id": 394,
    "slug": "rental-services",
    "name": "Rental Services",
    "path": "Services > Rental Services",
    "group": "Services"
  },
  {
    "id": 273,
    "slug": "repair-services",
    "name": "Repair Services",
    "path": "Services > Repair Services",
    "group": "Services"
  },
  {
    "id": 157,
    "slug": "tax-and-financial-services",
    "name": "Tax & Financial Services",
    "path": "Services > Tax & Financial Services",
    "group": "Services"
  },
  {
    "id": 158,
    "slug": "travel-agents-and-tours",
    "name": "Travel Agents & Tours",
    "path": "Services > Travel Agents & Tours",
    "group": "Services"
  },
  {
    "id": 159,
    "slug": "wedding-venues-and-services",
    "name": "Wedding Venues & Services",
    "path": "Services > Wedding Venues & Services",
    "group": "Services"
  },
  {
    "id": 161,
    "slug": "other-services",
    "name": "Other Services",
    "path": "Services > Other Services",
    "group": "Services"
  },
  {
    "id": 404,
    "slug": "business-and-industry",
    "name": "Business & Industry",
    "path": "Business & Industry",
    "group": "Business & Industry"
  },
  {
    "id": 405,
    "slug": "business-for-sale-and-investment",
    "name": "Business for Sale & Investment",
    "path": "Business & Industry > Business for Sale & Investment",
    "group": "Business & Industry"
  },
  {
    "id": 406,
    "slug": "wholesale-and-bulk",
    "name": "Wholesale & Bulk",
    "path": "Business & Industry > Wholesale & Bulk",
    "group": "Business & Industry"
  },
  {
    "id": 47,
    "slug": "jobs",
    "name": "Jobs",
    "path": "Jobs",
    "group": "Jobs"
  },
  {
    "id": 78,
    "slug": "accounting-and-finance-jobs",
    "name": "Accounting & Finance Jobs",
    "path": "Jobs > Accounting & Finance Jobs",
    "group": "Jobs"
  },
  {
    "id": 79,
    "slug": "advertising-and-marketing-jobs",
    "name": "Advertising & Marketing Jobs",
    "path": "Jobs > Advertising & Marketing Jobs",
    "group": "Jobs"
  },
  {
    "id": 80,
    "slug": "arts-and-entertainment-jobs",
    "name": "Arts & Entertainment Jobs",
    "path": "Jobs > Arts & Entertainment Jobs",
    "group": "Jobs"
  },
  {
    "id": 81,
    "slug": "childcare-and-babysitting-jobs",
    "name": "Childcare & Babysitting Jobs",
    "path": "Jobs > Childcare & Babysitting Jobs",
    "group": "Jobs"
  },
  {
    "id": 82,
    "slug": "clerical-and-administrative-jobs",
    "name": "Clerical & Administrative Jobs",
    "path": "Jobs > Clerical & Administrative Jobs",
    "group": "Jobs"
  },
  {
    "id": 83,
    "slug": "computing-and-it-jobs",
    "name": "Computing & IT Jobs",
    "path": "Jobs > Computing & IT Jobs",
    "group": "Jobs"
  },
  {
    "id": 84,
    "slug": "construction-and-skilled-trade-jobs",
    "name": "Construction & Skilled Trade Jobs",
    "path": "Jobs > Construction & Skilled Trade Jobs",
    "group": "Jobs"
  },
  {
    "id": 306,
    "slug": "consulting-and-strategy-jobs",
    "name": "Consulting & Strategy Jobs",
    "path": "Jobs > Consulting & Strategy Jobs",
    "group": "Jobs"
  },
  {
    "id": 85,
    "slug": "customer-service-jobs",
    "name": "Customer Services Jobs",
    "path": "Jobs > Customer Services Jobs",
    "group": "Jobs"
  },
  {
    "id": 166,
    "slug": "driver-jobs",
    "name": "Driver Jobs",
    "path": "Jobs > Driver Jobs",
    "group": "Jobs"
  },
  {
    "id": 86,
    "slug": "engineering-and-architecture-jobs",
    "name": "Engineering & Architecture Jobs",
    "path": "Jobs > Engineering & Architecture Jobs",
    "group": "Jobs"
  },
  {
    "id": 87,
    "slug": "farming-and-veterinary-jobs",
    "name": "Farming & Veterinary Jobs",
    "path": "Jobs > Farming & Veterinary Jobs",
    "group": "Jobs"
  },
  {
    "id": 88,
    "slug": "gardening-and-landscaping-jobs",
    "name": "Gardening & Landscaping Jobs",
    "path": "Jobs > Gardening & Landscaping Jobs",
    "group": "Jobs"
  },
  {
    "id": 89,
    "slug": "health-and-beauty-jobs",
    "name": "Health & Beauty Jobs",
    "path": "Jobs > Health & Beauty Jobs",
    "group": "Jobs"
  },
  {
    "id": 90,
    "slug": "healthcare-and-nursing-jobs",
    "name": "Healthcare & Nursing Jobs",
    "path": "Jobs > Healthcare & Nursing Jobs",
    "group": "Jobs"
  },
  {
    "id": 91,
    "slug": "hotel-jobs",
    "name": "Hotel Jobs",
    "path": "Jobs > Hotel Jobs",
    "group": "Jobs"
  },
  {
    "id": 92,
    "slug": "housekeeping-and-cleaning-jobs",
    "name": "Housekeeping & Cleaning Jobs",
    "path": "Jobs > Housekeeping & Cleaning Jobs",
    "group": "Jobs"
  },
  {
    "id": 93,
    "slug": "human-resources-jobs",
    "name": "Human Resources Jobs",
    "path": "Jobs > Human Resources Jobs",
    "group": "Jobs"
  },
  {
    "id": 94,
    "slug": "internship-jobs",
    "name": "Internship Jobs",
    "path": "Jobs > Internship Jobs",
    "group": "Jobs"
  },
  {
    "id": 95,
    "slug": "legal-jobs",
    "name": "Legal Jobs",
    "path": "Jobs > Legal Jobs",
    "group": "Jobs"
  },
  {
    "id": 96,
    "slug": "logistics-and-transportation-jobs",
    "name": "Logistics & Transportation Jobs",
    "path": "Jobs > Logistics & Transportation Jobs",
    "group": "Jobs"
  },
  {
    "id": 307,
    "slug": "management-jobs",
    "name": "Management Jobs",
    "path": "Jobs > Management Jobs",
    "group": "Jobs"
  },
  {
    "id": 97,
    "slug": "manual-labour-jobs",
    "name": "Manual Labour Jobs",
    "path": "Jobs > Manual Labour Jobs",
    "group": "Jobs"
  },
  {
    "id": 98,
    "slug": "manufacturing-jobs",
    "name": "Manufacturing Jobs",
    "path": "Jobs > Manufacturing Jobs",
    "group": "Jobs"
  },
  {
    "id": 99,
    "slug": "mining-industry-jobs",
    "name": "Mining Industry Jobs",
    "path": "Jobs > Mining Industry Jobs",
    "group": "Jobs"
  },
  {
    "id": 100,
    "slug": "office-jobs",
    "name": "Office Jobs",
    "path": "Jobs > Office Jobs",
    "group": "Jobs"
  },
  {
    "id": 101,
    "slug": "part-time-and-weekend-jobs",
    "name": "Part-Time & Weekend Jobs",
    "path": "Jobs > Part-Time & Weekend Jobs",
    "group": "Jobs"
  },
  {
    "id": 308,
    "slug": "quality-control-and-assurance-jobs",
    "name": "Quality Control & Assurance Jobs",
    "path": "Jobs > Quality Control & Assurance Jobs",
    "group": "Jobs"
  },
  {
    "id": 309,
    "slug": "research-and-survey-jobs",
    "name": "Research & Survey Jobs",
    "path": "Jobs > Research & Survey Jobs",
    "group": "Jobs"
  },
  {
    "id": 102,
    "slug": "restaurant-and-bar-jobs",
    "name": "Restaurant & Bar Jobs",
    "path": "Jobs > Restaurant & Bar Jobs",
    "group": "Jobs"
  },
  {
    "id": 103,
    "slug": "retail-jobs",
    "name": "Retail Jobs",
    "path": "Jobs > Retail Jobs",
    "group": "Jobs"
  },
  {
    "id": 104,
    "slug": "sales-and-telemarketing-jobs",
    "name": "Sales & Telemarketing Jobs",
    "path": "Jobs > Sales & Telemarketing Jobs",
    "group": "Jobs"
  },
  {
    "id": 105,
    "slug": "security-jobs",
    "name": "Security Jobs",
    "path": "Jobs > Security Jobs",
    "group": "Jobs"
  },
  {
    "id": 106,
    "slug": "sports-club-jobs",
    "name": "Sports Club Jobs",
    "path": "Jobs > Sports Club Jobs",
    "group": "Jobs"
  },
  {
    "id": 107,
    "slug": "teaching-jobs",
    "name": "Teaching Jobs",
    "path": "Jobs > Teaching Jobs",
    "group": "Jobs"
  },
  {
    "id": 167,
    "slug": "technology-jobs",
    "name": "Technology Jobs",
    "path": "Jobs > Technology Jobs",
    "group": "Jobs"
  },
  {
    "id": 108,
    "slug": "travel-and-tourism-jobs",
    "name": "Travel & Tourism Jobs",
    "path": "Jobs > Travel & Tourism Jobs",
    "group": "Jobs"
  },
  {
    "id": 109,
    "slug": "other-jobs",
    "name": "Other Jobs",
    "path": "Jobs > Other Jobs",
    "group": "Jobs"
  },
  {
    "id": 59,
    "slug": "babies-and-kids",
    "name": "Babies & Kids",
    "path": "Babies & Kids",
    "group": "Babies & Kids"
  },
  {
    "id": 250,
    "slug": "babies-and-kids-accessories",
    "name": "Baby & Kids' Accessories",
    "path": "Babies & Kids > Baby & Kids' Accessories",
    "group": "Babies & Kids"
  },
  {
    "id": 249,
    "slug": "baby-care",
    "name": "Care & Feeding",
    "path": "Babies & Kids > Care & Feeding",
    "group": "Babies & Kids"
  },
  {
    "id": 60,
    "slug": "childrens-clothing",
    "name": "Children's Clothing",
    "path": "Babies & Kids > Children's Clothing",
    "group": "Babies & Kids"
  },
  {
    "id": 62,
    "slug": "childrens-furniture",
    "name": "Children's Furniture",
    "path": "Babies & Kids > Children's Furniture",
    "group": "Babies & Kids"
  },
  {
    "id": 65,
    "slug": "childrens-gear-and-safety",
    "name": "Baby Gear & Equipment",
    "path": "Babies & Kids > Baby Gear & Equipment",
    "group": "Babies & Kids"
  },
  {
    "id": 61,
    "slug": "childrens-shoes",
    "name": "Children's Shoes",
    "path": "Babies & Kids > Children's Shoes",
    "group": "Babies & Kids"
  },
  {
    "id": 66,
    "slug": "maternity-and-pregnancy",
    "name": "Maternity & Pregnancy",
    "path": "Babies & Kids > Maternity & Pregnancy",
    "group": "Babies & Kids"
  },
  {
    "id": 64,
    "slug": "prams-and-strollers",
    "name": "Transport & Safety",
    "path": "Babies & Kids > Transport & Safety",
    "group": "Babies & Kids"
  },
  {
    "id": 393,
    "slug": "playground-equipment",
    "name": "Playground Equipment",
    "path": "Babies & Kids > Playground Equipment",
    "group": "Babies & Kids"
  },
  {
    "id": 67,
    "slug": "toys",
    "name": "Toys & Games",
    "path": "Babies & Kids > Toys & Games",
    "group": "Babies & Kids"
  },
  {
    "id": 7,
    "slug": "animals-and-pets",
    "name": "Pets",
    "path": "Pets",
    "group": "Pets"
  },
  {
    "id": 71,
    "slug": "birds",
    "name": "Birds",
    "path": "Pets > Birds",
    "group": "Pets"
  },
  {
    "id": 70,
    "slug": "cats-and-kittens",
    "name": "Cats & Kittens",
    "path": "Pets > Cats & Kittens",
    "group": "Pets"
  },
  {
    "id": 33,
    "slug": "dogs-and-puppies",
    "name": "Dogs & Puppies",
    "path": "Pets > Dogs & Puppies",
    "group": "Pets"
  },
  {
    "id": 72,
    "slug": "fish",
    "name": "Fish",
    "path": "Pets > Fish",
    "group": "Pets"
  },
  {
    "id": 35,
    "slug": "pets-accessories",
    "name": "Pet Accessories",
    "path": "Pets > Pet Accessories",
    "group": "Pets"
  },
  {
    "id": 34,
    "slug": "other-animals",
    "name": "Other Animals",
    "path": "Pets > Other Animals",
    "group": "Pets"
  },
  {
    "id": 24,
    "slug": "agriculture-and-foodstuff",
    "name": "Food, Agriculture & Farming",
    "path": "Food, Agriculture & Farming",
    "group": "Food, Agriculture & Farming"
  },
  {
    "id": 293,
    "slug": "farm-animal-feed-supplements",
    "name": "Farm Animal Feed & Supplements",
    "path": "Food, Agriculture & Farming > Farm Animal Feed & Supplements",
    "group": "Food, Agriculture & Farming"
  },
  {
    "id": 289,
    "slug": "farm-machinery-equipment",
    "name": "Farm Machinery & Equipment",
    "path": "Food, Agriculture & Farming > Farm Machinery & Equipment",
    "group": "Food, Agriculture & Farming"
  },
  {
    "id": 288,
    "slug": "feeds-supplements-seeds",
    "name": "Seeds & Fertilizers",
    "path": "Food, Agriculture & Farming > Seeds & Fertilizers",
    "group": "Food, Agriculture & Farming"
  },
  {
    "id": 74,
    "slug": "livestock-and-poultry",
    "name": "Farm Animals",
    "path": "Food, Agriculture & Farming > Farm Animals",
    "group": "Food, Agriculture & Farming"
  },
  {
    "id": 287,
    "slug": "meals-and-drinks",
    "name": "Food & Beverages",
    "path": "Food, Agriculture & Farming > Food & Beverages",
    "group": "Food, Agriculture & Farming"
  },
  {
    "id": 23,
    "slug": "office-and-commercial-equipment-tools",
    "name": "Commercial Equipment & Tools",
    "path": "Commercial Equipment & Tools",
    "group": "Commercial Equipment & Tools"
  },
  {
    "id": 301,
    "slug": "manufacturing-equipments",
    "name": "Manufacturing Equipment",
    "path": "Commercial Equipment & Tools > Manufacturing Equipment",
    "group": "Commercial Equipment & Tools"
  },
  {
    "id": 310,
    "slug": "manufacturing-materials-and-tools",
    "name": "Manufacturing Materials & Supplies",
    "path": "Commercial Equipment & Tools > Manufacturing Materials & Supplies",
    "group": "Commercial Equipment & Tools"
  },
  {
    "id": 302,
    "slug": "medical-equipment",
    "name": "Medical Equipment & Supplies",
    "path": "Commercial Equipment & Tools > Medical Equipment & Supplies",
    "group": "Commercial Equipment & Tools"
  },
  {
    "id": 304,
    "slug": "printing-equipment",
    "name": "Printing & Graphics Equipment",
    "path": "Commercial Equipment & Tools > Printing & Graphics Equipment",
    "group": "Commercial Equipment & Tools"
  },
  {
    "id": 300,
    "slug": "restaurant-and-catering-equipment",
    "name": "Restaurant & Catering Equipment",
    "path": "Commercial Equipment & Tools > Restaurant & Catering Equipment",
    "group": "Commercial Equipment & Tools"
  },
  {
    "id": 303,
    "slug": "safety-equipment",
    "name": "Safety Equipment & Protective Gear",
    "path": "Commercial Equipment & Tools > Safety Equipment & Protective Gear",
    "group": "Commercial Equipment & Tools"
  },
  {
    "id": 305,
    "slug": "salon-equipment",
    "name": "Salon & Beauty Equipment",
    "path": "Commercial Equipment & Tools > Salon & Beauty Equipment",
    "group": "Commercial Equipment & Tools"
  },
  {
    "id": 349,
    "slug": "stage-lighting-and-effects",
    "name": "Stage & Event Equipment",
    "path": "Commercial Equipment & Tools > Stage & Event Equipment",
    "group": "Commercial Equipment & Tools"
  },
  {
    "id": 285,
    "slug": "stationery",
    "name": "Stationery & Office Equipment",
    "path": "Commercial Equipment & Tools > Stationery & Office Equipment",
    "group": "Commercial Equipment & Tools"
  },
  {
    "id": 299,
    "slug": "store-equipments",
    "name": "Retail & Store Equipment",
    "path": "Commercial Equipment & Tools > Retail & Store Equipment",
    "group": "Commercial Equipment & Tools"
  },
  {
    "id": 290,
    "slug": "repair-and-construction",
    "name": "Repair & Construction",
    "path": "Repair & Construction",
    "group": "Repair & Construction"
  },
  {
    "id": 398,
    "slug": "hardware-and-fasteners",
    "name": "Hardware & Fasteners",
    "path": "Repair & Construction > Hardware & Fasteners",
    "group": "Repair & Construction"
  },
  {
    "id": 165,
    "slug": "building-materials",
    "name": "Building Materials & Supplies",
    "path": "Repair & Construction > Building Materials & Supplies",
    "group": "Repair & Construction"
  },
  {
    "id": 263,
    "slug": "doors",
    "name": "Doors & Security",
    "path": "Repair & Construction > Doors & Security",
    "group": "Repair & Construction"
  },
  {
    "id": 297,
    "slug": "power-equipments",
    "name": "Electrical Equipment",
    "path": "Repair & Construction > Electrical Equipment",
    "group": "Repair & Construction"
  },
  {
    "id": 272,
    "slug": "solar-energy-products",
    "name": "Solar Energy",
    "path": "Repair & Construction > Electrical Equipment > Solar Energy",
    "group": "Repair & Construction"
  },
  {
    "id": 294,
    "slug": "power-tools",
    "name": "Electrical Hand Tools",
    "path": "Repair & Construction > Electrical Hand Tools",
    "group": "Repair & Construction"
  },
  {
    "id": 281,
    "slug": "hand-and-power-tools",
    "name": "Hand Tools",
    "path": "Repair & Construction > Hand Tools",
    "group": "Repair & Construction"
  },
  {
    "id": 291,
    "slug": "measuring-and-layout-tools",
    "name": "Measuring & Testing Tools",
    "path": "Repair & Construction > Measuring & Testing Tools",
    "group": "Repair & Construction"
  },
  {
    "id": 296,
    "slug": "plumbing-and-water-supply",
    "name": "Plumbing & Water Systems",
    "path": "Repair & Construction > Plumbing & Water Systems",
    "group": "Repair & Construction"
  },
  {
    "id": 292,
    "slug": "windows",
    "name": "Windows & Glass",
    "path": "Repair & Construction > Windows & Glass",
    "group": "Repair & Construction"
  },
  {
    "id": 173,
    "slug": "other-repair-and-constraction-items",
    "name": "Other Repair & Construction Items",
    "path": "Repair & Construction > Other Repair & Construction Items",
    "group": "Repair & Construction"
  }
];

export const TAXONOMY_GROUPS: { group: string; categories: string[] }[] = [
  {
    "group": "Vehicles",
    "categories": [
      "Vehicles",
      "Vehicles > Cars",
      "Vehicles > Buses & Microbuses",
      "Vehicles > Construction & Heavy Machinery",
      "Vehicles > Motorcycles & Scooters",
      "Vehicles > Trucks & Trailers",
      "Vehicles > Vehicle Parts & Accessories",
      "Vehicles > Watercraft & Boats"
    ]
  },
  {
    "group": "Property",
    "categories": [
      "Property",
      "Property > New Builds",
      "Property > Houses & Apartments for Rent",
      "Property > Houses & Apartments for Sale",
      "Property > Land & Plots for Rent",
      "Property > Land & Plots for Sale",
      "Property > Commercial Property for Rent",
      "Property > Commercial Property for Sale",
      "Property > Event Centres, Venues & Workstations",
      "Property > Short Let Property"
    ]
  },
  {
    "group": "Phones & Tablets",
    "categories": [
      "Phones & Tablets",
      "Phones & Tablets > Mobile Phones",
      "Phones & Tablets > Accessories for Phones & Tablets",
      "Phones & Tablets > Smart Watches",
      "Phones & Tablets > Tablets"
    ]
  },
  {
    "group": "Electronics",
    "categories": [
      "Electronics",
      "Electronics > Accessories & Supplies for Electronics",
      "Electronics > Laptops & Computers",
      "Electronics > TV & DVD Equipment",
      "Electronics > Audio & Music Equipment",
      "Electronics > Computer Accessories ",
      "Electronics > Computer Hardware",
      "Electronics > Monitors",
      "Electronics > Headphones",
      "Electronics > Networking Products",
      "Electronics > Photo & Video Cameras",
      "Electronics > Printers & Scanners",
      "Electronics > Security & Surveillance",
      "Electronics > Software",
      "Electronics > Video Games",
      "Electronics > Video Game Consoles"
    ]
  },
  {
    "group": "Home, Furniture & Appliances",
    "categories": [
      "Home, Furniture & Appliances",
      "Home, Furniture & Appliances > Lighting",
      "Home, Furniture & Appliances > Storage & Organization",
      "Home, Furniture & Appliances > Furniture",
      "Home, Furniture & Appliances > Garden Supplies",
      "Home, Furniture & Appliances > Home Accessories",
      "Home, Furniture & Appliances > Home Appliances",
      "Home, Furniture & Appliances > Kitchen Appliances",
      "Home, Furniture & Appliances > Kitchenware & Cookware",
      "Home, Furniture & Appliances > Household Chemicals"
    ]
  },
  {
    "group": "Beauty & Personal Care",
    "categories": [
      "Beauty & Personal Care",
      "Beauty & Personal Care > Oral Care",
      "Beauty & Personal Care > Body Care",
      "Beauty & Personal Care > Fragrances",
      "Beauty & Personal Care > Hair Beauty",
      "Beauty & Personal Care > Make-Up",
      "Beauty & Personal Care > Sexual Wellness",
      "Beauty & Personal Care > Face Care",
      "Beauty & Personal Care > Tools & Accessories",
      "Beauty & Personal Care > Vitamins & Supplements"
    ]
  },
  {
    "group": "Fashion",
    "categories": [
      "Fashion",
      "Fashion > Bags",
      "Fashion > Clothing",
      "Fashion > Clothing Accessories",
      "Fashion > Jewelry",
      "Fashion > Shoes",
      "Fashion > Watches",
      "Fashion > Wedding Wear & Accessories"
    ]
  },
  {
    "group": "Leisure & Activities",
    "categories": [
      "Leisure & Activities",
      "Leisure & Activities > Massagers",
      "Leisure & Activities > Arts, Crafts & Awards",
      "Leisure & Activities > Books & Table Games",
      "Leisure & Activities > Outdoor Gear",
      "Leisure & Activities > Music & Video",
      "Leisure & Activities > Musical Instruments & Gear",
      "Leisure & Activities > Sports Equipment",
      "Leisure & Activities > Personal Mobility",
      "Leisure & Activities > Smoking Accessories"
    ]
  },
  {
    "group": "Seeking Work CVs",
    "categories": [
      "Seeking Work CVs",
      "Seeking Work CVs > Accounting & Finance CVs",
      "Seeking Work CVs > Advertising & Marketing CVs",
      "Seeking Work CVs > Arts & Entertainment CVs",
      "Seeking Work CVs > Childcare & Babysitting CVs",
      "Seeking Work CVs > Clerical & Administrative CVs",
      "Seeking Work CVs > Computing & IT CVs",
      "Seeking Work CVs > Construction & Skilled Trade CVs",
      "Seeking Work CVs > Consulting & Strategy CVs",
      "Seeking Work CVs > Customer Services CVs",
      "Seeking Work CVs > Driver CVs",
      "Seeking Work CVs > Engineering & Architecture CVs",
      "Seeking Work CVs > Farming & Veterinary CVs",
      "Seeking Work CVs > Gardening & Landscaping CVs",
      "Seeking Work CVs > Health & Beauty CVs",
      "Seeking Work CVs > Healthcare & Nursing CVs",
      "Seeking Work CVs > Hotel CVs",
      "Seeking Work CVs > Housekeeping & Cleaning CVs",
      "Seeking Work CVs > Human Resources CVs",
      "Seeking Work CVs > Internship CVs",
      "Seeking Work CVs > Legal CVs",
      "Seeking Work CVs > Logistics & Transportation CVs",
      "Seeking Work CVs > Management CVs",
      "Seeking Work CVs > Manual Labour CVs",
      "Seeking Work CVs > Manufacturing CVs",
      "Seeking Work CVs > Mining Industry CVs",
      "Seeking Work CVs > Office CVs",
      "Seeking Work CVs > Part-Time & Weekend CVs",
      "Seeking Work CVs > Quality Control & Assurance CVs",
      "Seeking Work CVs > Research & Survey CVs",
      "Seeking Work CVs > Restaurant & Bar CVs",
      "Seeking Work CVs > Retail CVs",
      "Seeking Work CVs > Sales & Telemarketing CVs",
      "Seeking Work CVs > Security CVs",
      "Seeking Work CVs > Sports Club CVs",
      "Seeking Work CVs > Teaching CVs",
      "Seeking Work CVs > Technology CVs",
      "Seeking Work CVs > Travel & Tourism CVs",
      "Seeking Work CVs > Other CVs"
    ]
  },
  {
    "group": "Services",
    "categories": [
      "Services",
      "Services > Automotive Services",
      "Services > Building & Trade Services",
      "Services > Chauffeur & Airport Transfer Services",
      "Services > Child Care & Education Services",
      "Services > Classes & Courses",
      "Services > Cleaning Services",
      "Services > Computer & IT Services",
      "Services > DJ & Entertainment Services",
      "Services > Fitness & Personal Training Services",
      "Services > Health & Beauty Services",
      "Services > Landscaping & Gardening Services",
      "Services > Legal Services",
      "Services > Logistics Services",
      "Services > Manufacturing Services",
      "Services > Party, Catering & Event Services",
      "Services > Pet Services",
      "Services > Photography & Video Services",
      "Services > Printing Services",
      "Services > Recruitment Services",
      "Services > Rental Services",
      "Services > Repair Services",
      "Services > Tax & Financial Services",
      "Services > Travel Agents & Tours",
      "Services > Wedding Venues & Services",
      "Services > Other Services"
    ]
  },
  {
    "group": "Business & Industry",
    "categories": [
      "Business & Industry",
      "Business & Industry > Business for Sale & Investment",
      "Business & Industry > Wholesale & Bulk"
    ]
  },
  {
    "group": "Jobs",
    "categories": [
      "Jobs",
      "Jobs > Accounting & Finance Jobs",
      "Jobs > Advertising & Marketing Jobs",
      "Jobs > Arts & Entertainment Jobs",
      "Jobs > Childcare & Babysitting Jobs",
      "Jobs > Clerical & Administrative Jobs",
      "Jobs > Computing & IT Jobs",
      "Jobs > Construction & Skilled Trade Jobs",
      "Jobs > Consulting & Strategy Jobs",
      "Jobs > Customer Services Jobs",
      "Jobs > Driver Jobs",
      "Jobs > Engineering & Architecture Jobs",
      "Jobs > Farming & Veterinary Jobs",
      "Jobs > Gardening & Landscaping Jobs",
      "Jobs > Health & Beauty Jobs",
      "Jobs > Healthcare & Nursing Jobs",
      "Jobs > Hotel Jobs",
      "Jobs > Housekeeping & Cleaning Jobs",
      "Jobs > Human Resources Jobs",
      "Jobs > Internship Jobs",
      "Jobs > Legal Jobs",
      "Jobs > Logistics & Transportation Jobs",
      "Jobs > Management Jobs",
      "Jobs > Manual Labour Jobs",
      "Jobs > Manufacturing Jobs",
      "Jobs > Mining Industry Jobs",
      "Jobs > Office Jobs",
      "Jobs > Part-Time & Weekend Jobs",
      "Jobs > Quality Control & Assurance Jobs",
      "Jobs > Research & Survey Jobs",
      "Jobs > Restaurant & Bar Jobs",
      "Jobs > Retail Jobs",
      "Jobs > Sales & Telemarketing Jobs",
      "Jobs > Security Jobs",
      "Jobs > Sports Club Jobs",
      "Jobs > Teaching Jobs",
      "Jobs > Technology Jobs",
      "Jobs > Travel & Tourism Jobs",
      "Jobs > Other Jobs"
    ]
  },
  {
    "group": "Babies & Kids",
    "categories": [
      "Babies & Kids",
      "Babies & Kids > Baby & Kids' Accessories",
      "Babies & Kids > Care & Feeding",
      "Babies & Kids > Children's Clothing",
      "Babies & Kids > Children's Furniture",
      "Babies & Kids > Baby Gear & Equipment",
      "Babies & Kids > Children's Shoes",
      "Babies & Kids > Maternity & Pregnancy",
      "Babies & Kids > Transport & Safety",
      "Babies & Kids > Playground Equipment",
      "Babies & Kids > Toys & Games"
    ]
  },
  {
    "group": "Pets",
    "categories": [
      "Pets",
      "Pets > Birds",
      "Pets > Cats & Kittens",
      "Pets > Dogs & Puppies",
      "Pets > Fish",
      "Pets > Pet Accessories",
      "Pets > Other Animals"
    ]
  },
  {
    "group": "Food, Agriculture & Farming",
    "categories": [
      "Food, Agriculture & Farming",
      "Food, Agriculture & Farming > Farm Animal Feed & Supplements",
      "Food, Agriculture & Farming > Farm Machinery & Equipment",
      "Food, Agriculture & Farming > Seeds & Fertilizers",
      "Food, Agriculture & Farming > Farm Animals",
      "Food, Agriculture & Farming > Food & Beverages"
    ]
  },
  {
    "group": "Commercial Equipment & Tools",
    "categories": [
      "Commercial Equipment & Tools",
      "Commercial Equipment & Tools > Manufacturing Equipment",
      "Commercial Equipment & Tools > Manufacturing Materials & Supplies",
      "Commercial Equipment & Tools > Medical Equipment & Supplies",
      "Commercial Equipment & Tools > Printing & Graphics Equipment",
      "Commercial Equipment & Tools > Restaurant & Catering Equipment",
      "Commercial Equipment & Tools > Safety Equipment & Protective Gear",
      "Commercial Equipment & Tools > Salon & Beauty Equipment",
      "Commercial Equipment & Tools > Stage & Event Equipment",
      "Commercial Equipment & Tools > Stationery & Office Equipment",
      "Commercial Equipment & Tools > Retail & Store Equipment"
    ]
  },
  {
    "group": "Repair & Construction",
    "categories": [
      "Repair & Construction",
      "Repair & Construction > Hardware & Fasteners",
      "Repair & Construction > Building Materials & Supplies",
      "Repair & Construction > Doors & Security",
      "Repair & Construction > Electrical Equipment",
      "Repair & Construction > Electrical Equipment > Solar Energy",
      "Repair & Construction > Electrical Hand Tools",
      "Repair & Construction > Hand Tools",
      "Repair & Construction > Measuring & Testing Tools",
      "Repair & Construction > Plumbing & Water Systems",
      "Repair & Construction > Windows & Glass",
      "Repair & Construction > Other Repair & Construction Items"
    ]
  }
];

/** All category paths as flat strings ("Vehicles > Cars") for search/validation. */
export const ALL_TAXONOMY_CATEGORIES: string[] = TAXONOMY_ENTRIES.map((e) => e.path);

/** Look up a taxonomy entry by its path label. */
export function taxonomyEntryByPath(path: string): TaxonomyEntry | undefined {
  return TAXONOMY_ENTRIES.find((e) => e.path === path);
}

/** Look up a taxonomy entry by its Jiji slug. */
export function taxonomyEntryBySlug(slug: string): TaxonomyEntry | undefined {
  return TAXONOMY_ENTRIES.find((e) => e.slug === slug);
}

